name: CI

on:
  push:
    branches: [dev, master]

jobs:
  
  ci-docs:
    runs-on: ubuntu-latest
    steps:
    - name: downloading last version
      uses: actions/checkout@v1
    - name: setting up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: upgrade pip
      run: python -m pip install --upgrade pip
    - name: install package dependencies
      run: pip install .
    - name: install doc dependencies
      run: pip install .[docs]
    - name: run doc tests
      run: cd docs; make html
  
  ci-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: downloading last version
      uses: actions/checkout@v1
    - name: setting up python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: upgrade pip
      run: python -m pip install --upgrade pip
    - name: install package dependencies
      run: pip install .
    - name: install test dependencies
      run: pip install .[tests]
    - name: run CI tests
      env:
        TEST_CSV: ${{ secrets.TEST_CSV }}
        TEST_JSON: ${{ secrets.TEST_JSON }}
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        DEEPINT_TOKEN: ${{ secrets.DEEPINT_TOKEN }}
        DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_ORGANIZATION }}
        TEST_EXTERNAL_SOURCE_URL: ${{ secrets.TEST_EXTERNAL_SOURCE_URL }}
      working-directory: tests
      run: python -m pytest test.py
