name: release new version

on:
  push:
    branches: master

jobs:
  install:
    steps:
    - name: download last changes
      uses: actions/checkout@v1
    - name: setting up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install package dependencies
      run: pip install .
    - name: install package doc dependencies
      run: pip install .[docs]
  release-pipy:
    needs: install
    steps:
    - name: build
      run: python setup.py sdist bdist_wheel
    - name: release on pipy
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
